import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import "./globals.css";
import BaseLayout from "./comps/BaseLayout";
import GlobalProvider from "./context/GlobalProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});
export const metadata = {
  title: "Dua & Ruqyah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalProvider>
          <BaseLayout>{children}</BaseLayout>
        </GlobalProvider>
      </body>
    </html>
  );
}
